// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkadwueobbxacelknxsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYWR3dWVvYmJ4YWNlbGtueHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjk5MDMsImV4cCI6MjA3MzYwNTkwM30.ym7xDoeQ6VV6beGFGBOkbUfWr9CLo16Qj6US-onbEPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});